# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.7
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class AgreementRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'agreement_code': 'AgreementCode',
        'agreement_fulltext': 'str',
        'content_id': 'str',
        'version': 'int'
    }

    attribute_map = {
        'agreement_code': 'agreementCode',
        'agreement_fulltext': 'agreementFulltext',
        'content_id': 'contentId',
        'version': 'version'
    }

    def __init__(self, agreement_code=None, agreement_fulltext=None, content_id=None, version=None, local_vars_configuration=None):  # noqa: E501
        """AgreementRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._agreement_code = None
        self._agreement_fulltext = None
        self._content_id = None
        self._version = None
        self.discriminator = None

        self.agreement_code = agreement_code
        self.agreement_fulltext = agreement_fulltext
        self.content_id = content_id
        self.version = version

    @property
    def agreement_code(self):
        """Gets the agreement_code of this AgreementRequest.  # noqa: E501


        :return: The agreement_code of this AgreementRequest.  # noqa: E501
        :rtype: AgreementCode
        """
        return self._agreement_code

    @agreement_code.setter
    def agreement_code(self, agreement_code):
        """Sets the agreement_code of this AgreementRequest.


        :param agreement_code: The agreement_code of this AgreementRequest.  # noqa: E501
        :type agreement_code: AgreementCode
        """
        if self.local_vars_configuration.client_side_validation and agreement_code is None:  # noqa: E501
            raise ValueError("Invalid value for `agreement_code`, must not be `None`")  # noqa: E501

        self._agreement_code = agreement_code

    @property
    def agreement_fulltext(self):
        """Gets the agreement_fulltext of this AgreementRequest.  # noqa: E501

        The full text of the agreement (currently `By clicking OK, I certify that I have the necessary rights to upload this content and that it will not infringe on any third-party legal or intellectual property rights.`).  # noqa: E501

        :return: The agreement_fulltext of this AgreementRequest.  # noqa: E501
        :rtype: str
        """
        return self._agreement_fulltext

    @agreement_fulltext.setter
    def agreement_fulltext(self, agreement_fulltext):
        """Sets the agreement_fulltext of this AgreementRequest.

        The full text of the agreement (currently `By clicking OK, I certify that I have the necessary rights to upload this content and that it will not infringe on any third-party legal or intellectual property rights.`).  # noqa: E501

        :param agreement_fulltext: The agreement_fulltext of this AgreementRequest.  # noqa: E501
        :type agreement_fulltext: str
        """
        if self.local_vars_configuration.client_side_validation and agreement_fulltext is None:  # noqa: E501
            raise ValueError("Invalid value for `agreement_fulltext`, must not be `None`")  # noqa: E501

        self._agreement_fulltext = agreement_fulltext

    @property
    def content_id(self):
        """Gets the content_id of this AgreementRequest.  # noqa: E501

        The id of the content being uploaded, such as a WorldID, AvatarID, or PropID.  # noqa: E501

        :return: The content_id of this AgreementRequest.  # noqa: E501
        :rtype: str
        """
        return self._content_id

    @content_id.setter
    def content_id(self, content_id):
        """Sets the content_id of this AgreementRequest.

        The id of the content being uploaded, such as a WorldID, AvatarID, or PropID.  # noqa: E501

        :param content_id: The content_id of this AgreementRequest.  # noqa: E501
        :type content_id: str
        """
        if self.local_vars_configuration.client_side_validation and content_id is None:  # noqa: E501
            raise ValueError("Invalid value for `content_id`, must not be `None`")  # noqa: E501

        self._content_id = content_id

    @property
    def version(self):
        """Gets the version of this AgreementRequest.  # noqa: E501

        The version of the agreement (currently `1`).  # noqa: E501

        :return: The version of this AgreementRequest.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this AgreementRequest.

        The version of the agreement (currently `1`).  # noqa: E501

        :param version: The version of this AgreementRequest.  # noqa: E501
        :type version: int
        """
        if self.local_vars_configuration.client_side_validation and version is None:  # noqa: E501
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgreementRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AgreementRequest):
            return True

        return self.to_dict() != other.to_dict()
