# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.8
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class CreateProductRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'display_name': 'str',
        'image_id': 'str',
        'product_type': 'ProductType',
        'tags': 'list[str]',
        'use_for_subscriber_list': 'bool'
    }

    attribute_map = {
        'description': 'description',
        'display_name': 'displayName',
        'image_id': 'imageId',
        'product_type': 'productType',
        'tags': 'tags',
        'use_for_subscriber_list': 'useForSubscriberList'
    }

    def __init__(self, description=None, display_name=None, image_id=None, product_type=None, tags=None, use_for_subscriber_list=None, local_vars_configuration=None):  # noqa: E501
        """CreateProductRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._display_name = None
        self._image_id = None
        self._product_type = None
        self._tags = None
        self._use_for_subscriber_list = None
        self.discriminator = None

        self.description = description
        self.display_name = display_name
        self.image_id = image_id
        self.product_type = product_type
        self.tags = tags
        self.use_for_subscriber_list = use_for_subscriber_list

    @property
    def description(self):
        """Gets the description of this CreateProductRequest.  # noqa: E501


        :return: The description of this CreateProductRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateProductRequest.


        :param description: The description of this CreateProductRequest.  # noqa: E501
        :type description: str
        """
        if self.local_vars_configuration.client_side_validation and description is None:  # noqa: E501
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def display_name(self):
        """Gets the display_name of this CreateProductRequest.  # noqa: E501


        :return: The display_name of this CreateProductRequest.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this CreateProductRequest.


        :param display_name: The display_name of this CreateProductRequest.  # noqa: E501
        :type display_name: str
        """
        if self.local_vars_configuration.client_side_validation and display_name is None:  # noqa: E501
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def image_id(self):
        """Gets the image_id of this CreateProductRequest.  # noqa: E501


        :return: The image_id of this CreateProductRequest.  # noqa: E501
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id):
        """Sets the image_id of this CreateProductRequest.


        :param image_id: The image_id of this CreateProductRequest.  # noqa: E501
        :type image_id: str
        """
        if self.local_vars_configuration.client_side_validation and image_id is None:  # noqa: E501
            raise ValueError("Invalid value for `image_id`, must not be `None`")  # noqa: E501

        self._image_id = image_id

    @property
    def product_type(self):
        """Gets the product_type of this CreateProductRequest.  # noqa: E501


        :return: The product_type of this CreateProductRequest.  # noqa: E501
        :rtype: ProductType
        """
        return self._product_type

    @product_type.setter
    def product_type(self, product_type):
        """Sets the product_type of this CreateProductRequest.


        :param product_type: The product_type of this CreateProductRequest.  # noqa: E501
        :type product_type: ProductType
        """
        if self.local_vars_configuration.client_side_validation and product_type is None:  # noqa: E501
            raise ValueError("Invalid value for `product_type`, must not be `None`")  # noqa: E501

        self._product_type = product_type

    @property
    def tags(self):
        """Gets the tags of this CreateProductRequest.  # noqa: E501


        :return: The tags of this CreateProductRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this CreateProductRequest.


        :param tags: The tags of this CreateProductRequest.  # noqa: E501
        :type tags: list[str]
        """
        if self.local_vars_configuration.client_side_validation and tags is None:  # noqa: E501
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags

    @property
    def use_for_subscriber_list(self):
        """Gets the use_for_subscriber_list of this CreateProductRequest.  # noqa: E501


        :return: The use_for_subscriber_list of this CreateProductRequest.  # noqa: E501
        :rtype: bool
        """
        return self._use_for_subscriber_list

    @use_for_subscriber_list.setter
    def use_for_subscriber_list(self, use_for_subscriber_list):
        """Sets the use_for_subscriber_list of this CreateProductRequest.


        :param use_for_subscriber_list: The use_for_subscriber_list of this CreateProductRequest.  # noqa: E501
        :type use_for_subscriber_list: bool
        """
        if self.local_vars_configuration.client_side_validation and use_for_subscriber_list is None:  # noqa: E501
            raise ValueError("Invalid value for `use_for_subscriber_list`, must not be `None`")  # noqa: E501

        self._use_for_subscriber_list = use_for_subscriber_list

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateProductRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateProductRequest):
            return True

        return self.to_dict() != other.to_dict()
