# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.5
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class DiscordDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'global_name': 'str',
        'id': 'str'
    }

    attribute_map = {
        'global_name': 'global_name',
        'id': 'id'
    }

    def __init__(self, global_name=None, id=None, local_vars_configuration=None):  # noqa: E501
        """DiscordDetails - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._global_name = None
        self._id = None
        self.discriminator = None

        if global_name is not None:
            self.global_name = global_name
        if id is not None:
            self.id = id

    @property
    def global_name(self):
        """Gets the global_name of this DiscordDetails.  # noqa: E501


        :return: The global_name of this DiscordDetails.  # noqa: E501
        :rtype: str
        """
        return self._global_name

    @global_name.setter
    def global_name(self, global_name):
        """Sets the global_name of this DiscordDetails.


        :param global_name: The global_name of this DiscordDetails.  # noqa: E501
        :type global_name: str
        """

        self._global_name = global_name

    @property
    def id(self):
        """Gets the id of this DiscordDetails.  # noqa: E501

        https://discord.com/developers/docs/reference#snowflakes  # noqa: E501

        :return: The id of this DiscordDetails.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DiscordDetails.

        https://discord.com/developers/docs/reference#snowflakes  # noqa: E501

        :param id: The id of this DiscordDetails.  # noqa: E501
        :type id: str
        """

        self._id = id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiscordDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DiscordDetails):
            return True

        return self.to_dict() != other.to_dict()
