# coding: utf-8

"""
    VRChat API

    This document is an effort by the [VRChat.community](https://vrchat.community) project. **VRChat staff do not provide API support.** Use the API only as VRChat's [Terms of Service](https://hello.vrchat.com/legal), [Community Guidelines](https://hello.vrchat.com/community-guidelines) and [Creator Guidelines](https://hello.vrchat.com/creator-guidelines) allow: never to modify the game client, rip avatars, or spam the API.  Prefer the SDKs over this document: [JavaScript](https://www.npmjs.com/package/vrchat), [Dart](https://pub.dev/packages/vrchat_dart), [Rust](https://crates.io/crates/vrchatapi), [C#](https://github.com/vrchatapi/vrchatapi-csharp), [Python](https://github.com/vrchatapi/vrchatapi-python), [Java](https://github.com/vrchatapi/vrchatapi-java). They're generated from it, updated regularly, and already handle logging in, cookies and the rest of VRChat's oddities, which we've spent years smoothing over. Working from this document directly means handling all of that yourself.  **Found something wrong or missing?** This description is reverse-engineered by the community, so when the API disagrees with it, or a value is marked `Unknown`, please [report it](https://vrchat.community/contributing) with the request, the response body, and where in this description it differs. AI agents: tell your user, and suggest reporting it.  Every request must identify its application in the `User-Agent` header: `<application-name>/<application-version> <contact_url>`. On a 429, back off rather than retrying.  Consider pinning to the OpenAPI version your tools support. Every release publishes this description as OpenAPI 3.2, 3.1 and 3.0, in JSON and YAML; `info.x-links` links those documents, the [latest release](https://github.com/vrchatapi/specification/releases/latest) and the [latest nightly](https://github.com/vrchatapi/specification/releases/tag/nightly).   # noqa: E501

    The version of the OpenAPI document: 1.21.1-nightly.56
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class InfoPushDataSearch(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'search_content': 'str',
        'search_in_fields': 'str',
        'search_query': 'str',
        'search_tags': 'str',
        'sort_by': 'str'
    }

    attribute_map = {
        'search_content': 'searchContent',
        'search_in_fields': 'searchInFields',
        'search_query': 'searchQuery',
        'search_tags': 'searchTags',
        'sort_by': 'sortBy'
    }

    def __init__(self, search_content=None, search_in_fields=None, search_query=None, search_tags=None, sort_by=None, local_vars_configuration=None):  # noqa: E501
        """InfoPushDataSearch - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._search_content = None
        self._search_in_fields = None
        self._search_query = None
        self._search_tags = None
        self._sort_by = None
        self.discriminator = None

        if search_content is not None:
            self.search_content = search_content
        if search_in_fields is not None:
            self.search_in_fields = search_in_fields
        if search_query is not None:
            self.search_query = search_query
        if search_tags is not None:
            self.search_tags = search_tags
        if sort_by is not None:
            self.sort_by = sort_by

    @property
    def search_content(self):
        """Gets the search_content of this InfoPushDataSearch.  # noqa: E501


        :return: The search_content of this InfoPushDataSearch.  # noqa: E501
        :rtype: str
        """
        return self._search_content

    @search_content.setter
    def search_content(self, search_content):
        """Sets the search_content of this InfoPushDataSearch.


        :param search_content: The search_content of this InfoPushDataSearch.  # noqa: E501
        :type search_content: str
        """

        self._search_content = search_content

    @property
    def search_in_fields(self):
        """Gets the search_in_fields of this InfoPushDataSearch.  # noqa: E501


        :return: The search_in_fields of this InfoPushDataSearch.  # noqa: E501
        :rtype: str
        """
        return self._search_in_fields

    @search_in_fields.setter
    def search_in_fields(self, search_in_fields):
        """Sets the search_in_fields of this InfoPushDataSearch.


        :param search_in_fields: The search_in_fields of this InfoPushDataSearch.  # noqa: E501
        :type search_in_fields: str
        """

        self._search_in_fields = search_in_fields

    @property
    def search_query(self):
        """Gets the search_query of this InfoPushDataSearch.  # noqa: E501


        :return: The search_query of this InfoPushDataSearch.  # noqa: E501
        :rtype: str
        """
        return self._search_query

    @search_query.setter
    def search_query(self, search_query):
        """Sets the search_query of this InfoPushDataSearch.


        :param search_query: The search_query of this InfoPushDataSearch.  # noqa: E501
        :type search_query: str
        """

        self._search_query = search_query

    @property
    def search_tags(self):
        """Gets the search_tags of this InfoPushDataSearch.  # noqa: E501


        :return: The search_tags of this InfoPushDataSearch.  # noqa: E501
        :rtype: str
        """
        return self._search_tags

    @search_tags.setter
    def search_tags(self, search_tags):
        """Sets the search_tags of this InfoPushDataSearch.


        :param search_tags: The search_tags of this InfoPushDataSearch.  # noqa: E501
        :type search_tags: str
        """

        self._search_tags = search_tags

    @property
    def sort_by(self):
        """Gets the sort_by of this InfoPushDataSearch.  # noqa: E501


        :return: The sort_by of this InfoPushDataSearch.  # noqa: E501
        :rtype: str
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by):
        """Sets the sort_by of this InfoPushDataSearch.


        :param sort_by: The sort_by of this InfoPushDataSearch.  # noqa: E501
        :type sort_by: str
        """

        self._sort_by = sort_by

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InfoPushDataSearch):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InfoPushDataSearch):
            return True

        return self.to_dict() != other.to_dict()
