# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.9
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class InfoPushDataArticle(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'content': 'list[InfoPushDataArticleContent]',
        'embedded_link_data': 'list[InfoPushEmbeddedLink]',
        'jump_links': 'list[str]',
        'more_info_links': 'list[InfoPushEmbeddedLink]',
        'section_links': 'list[str]'
    }

    attribute_map = {
        'content': 'content',
        'embedded_link_data': 'embeddedLinkData',
        'jump_links': 'jumpLinks',
        'more_info_links': 'moreInfoLinks',
        'section_links': 'sectionLinks'
    }

    def __init__(self, content=None, embedded_link_data=None, jump_links=None, more_info_links=None, section_links=None, local_vars_configuration=None):  # noqa: E501
        """InfoPushDataArticle - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._content = None
        self._embedded_link_data = None
        self._jump_links = None
        self._more_info_links = None
        self._section_links = None
        self.discriminator = None

        if content is not None:
            self.content = content
        if embedded_link_data is not None:
            self.embedded_link_data = embedded_link_data
        if jump_links is not None:
            self.jump_links = jump_links
        if more_info_links is not None:
            self.more_info_links = more_info_links
        if section_links is not None:
            self.section_links = section_links

    @property
    def content(self):
        """Gets the content of this InfoPushDataArticle.  # noqa: E501


        :return: The content of this InfoPushDataArticle.  # noqa: E501
        :rtype: list[InfoPushDataArticleContent]
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this InfoPushDataArticle.


        :param content: The content of this InfoPushDataArticle.  # noqa: E501
        :type content: list[InfoPushDataArticleContent]
        """

        self._content = content

    @property
    def embedded_link_data(self):
        """Gets the embedded_link_data of this InfoPushDataArticle.  # noqa: E501


        :return: The embedded_link_data of this InfoPushDataArticle.  # noqa: E501
        :rtype: list[InfoPushEmbeddedLink]
        """
        return self._embedded_link_data

    @embedded_link_data.setter
    def embedded_link_data(self, embedded_link_data):
        """Sets the embedded_link_data of this InfoPushDataArticle.


        :param embedded_link_data: The embedded_link_data of this InfoPushDataArticle.  # noqa: E501
        :type embedded_link_data: list[InfoPushEmbeddedLink]
        """

        self._embedded_link_data = embedded_link_data

    @property
    def jump_links(self):
        """Gets the jump_links of this InfoPushDataArticle.  # noqa: E501


        :return: The jump_links of this InfoPushDataArticle.  # noqa: E501
        :rtype: list[str]
        """
        return self._jump_links

    @jump_links.setter
    def jump_links(self, jump_links):
        """Sets the jump_links of this InfoPushDataArticle.


        :param jump_links: The jump_links of this InfoPushDataArticle.  # noqa: E501
        :type jump_links: list[str]
        """

        self._jump_links = jump_links

    @property
    def more_info_links(self):
        """Gets the more_info_links of this InfoPushDataArticle.  # noqa: E501


        :return: The more_info_links of this InfoPushDataArticle.  # noqa: E501
        :rtype: list[InfoPushEmbeddedLink]
        """
        return self._more_info_links

    @more_info_links.setter
    def more_info_links(self, more_info_links):
        """Sets the more_info_links of this InfoPushDataArticle.


        :param more_info_links: The more_info_links of this InfoPushDataArticle.  # noqa: E501
        :type more_info_links: list[InfoPushEmbeddedLink]
        """

        self._more_info_links = more_info_links

    @property
    def section_links(self):
        """Gets the section_links of this InfoPushDataArticle.  # noqa: E501


        :return: The section_links of this InfoPushDataArticle.  # noqa: E501
        :rtype: list[str]
        """
        return self._section_links

    @section_links.setter
    def section_links(self, section_links):
        """Sets the section_links of this InfoPushDataArticle.


        :param section_links: The section_links of this InfoPushDataArticle.  # noqa: E501
        :type section_links: list[str]
        """

        self._section_links = section_links

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InfoPushDataArticle):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InfoPushDataArticle):
            return True

        return self.to_dict() != other.to_dict()
