# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.21.1-nightly.40
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class InfoPushDataDeliveryBehavior(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'bypass24_hour_window': 'bool',
        'max_redelivery_attempts': 'int',
        'redeliver_if_no_engagement': 'bool'
    }

    attribute_map = {
        'bypass24_hour_window': 'bypass24HourWindow',
        'max_redelivery_attempts': 'maxRedeliveryAttempts',
        'redeliver_if_no_engagement': 'redeliverIfNoEngagement'
    }

    def __init__(self, bypass24_hour_window=None, max_redelivery_attempts=None, redeliver_if_no_engagement=None, local_vars_configuration=None):  # noqa: E501
        """InfoPushDataDeliveryBehavior - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._bypass24_hour_window = None
        self._max_redelivery_attempts = None
        self._redeliver_if_no_engagement = None
        self.discriminator = None

        if bypass24_hour_window is not None:
            self.bypass24_hour_window = bypass24_hour_window
        if max_redelivery_attempts is not None:
            self.max_redelivery_attempts = max_redelivery_attempts
        if redeliver_if_no_engagement is not None:
            self.redeliver_if_no_engagement = redeliver_if_no_engagement

    @property
    def bypass24_hour_window(self):
        """Gets the bypass24_hour_window of this InfoPushDataDeliveryBehavior.  # noqa: E501


        :return: The bypass24_hour_window of this InfoPushDataDeliveryBehavior.  # noqa: E501
        :rtype: bool
        """
        return self._bypass24_hour_window

    @bypass24_hour_window.setter
    def bypass24_hour_window(self, bypass24_hour_window):
        """Sets the bypass24_hour_window of this InfoPushDataDeliveryBehavior.


        :param bypass24_hour_window: The bypass24_hour_window of this InfoPushDataDeliveryBehavior.  # noqa: E501
        :type bypass24_hour_window: bool
        """

        self._bypass24_hour_window = bypass24_hour_window

    @property
    def max_redelivery_attempts(self):
        """Gets the max_redelivery_attempts of this InfoPushDataDeliveryBehavior.  # noqa: E501


        :return: The max_redelivery_attempts of this InfoPushDataDeliveryBehavior.  # noqa: E501
        :rtype: int
        """
        return self._max_redelivery_attempts

    @max_redelivery_attempts.setter
    def max_redelivery_attempts(self, max_redelivery_attempts):
        """Sets the max_redelivery_attempts of this InfoPushDataDeliveryBehavior.


        :param max_redelivery_attempts: The max_redelivery_attempts of this InfoPushDataDeliveryBehavior.  # noqa: E501
        :type max_redelivery_attempts: int
        """

        self._max_redelivery_attempts = max_redelivery_attempts

    @property
    def redeliver_if_no_engagement(self):
        """Gets the redeliver_if_no_engagement of this InfoPushDataDeliveryBehavior.  # noqa: E501


        :return: The redeliver_if_no_engagement of this InfoPushDataDeliveryBehavior.  # noqa: E501
        :rtype: bool
        """
        return self._redeliver_if_no_engagement

    @redeliver_if_no_engagement.setter
    def redeliver_if_no_engagement(self, redeliver_if_no_engagement):
        """Sets the redeliver_if_no_engagement of this InfoPushDataDeliveryBehavior.


        :param redeliver_if_no_engagement: The redeliver_if_no_engagement of this InfoPushDataDeliveryBehavior.  # noqa: E501
        :type redeliver_if_no_engagement: bool
        """

        self._redeliver_if_no_engagement = redeliver_if_no_engagement

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InfoPushDataDeliveryBehavior):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InfoPushDataDeliveryBehavior):
            return True

        return self.to_dict() != other.to_dict()
