# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.9
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class MutualFriend(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'avatar_thumbnail': 'str',
        'banner_color': 'str',
        'banner_type': 'str',
        'current_avatar_image_url': 'str',
        'current_avatar_tags': 'list[str]',
        'current_avatar_thumbnail_image_url': 'str',
        'display_name': 'str',
        'icon_frame': 'str',
        'icon_url': 'str',
        'id': 'str',
        'image_url': 'str',
        'nameplate_effect': 'str',
        'profile_effect': 'str',
        'profile_pic_override': 'str',
        'status': 'UserStatus',
        'status_description': 'str'
    }

    attribute_map = {
        'avatar_thumbnail': 'avatarThumbnail',
        'banner_color': 'bannerColor',
        'banner_type': 'bannerType',
        'current_avatar_image_url': 'currentAvatarImageUrl',
        'current_avatar_tags': 'currentAvatarTags',
        'current_avatar_thumbnail_image_url': 'currentAvatarThumbnailImageUrl',
        'display_name': 'displayName',
        'icon_frame': 'iconFrame',
        'icon_url': 'iconUrl',
        'id': 'id',
        'image_url': 'imageUrl',
        'nameplate_effect': 'nameplateEffect',
        'profile_effect': 'profileEffect',
        'profile_pic_override': 'profilePicOverride',
        'status': 'status',
        'status_description': 'statusDescription'
    }

    def __init__(self, avatar_thumbnail=None, banner_color=None, banner_type=None, current_avatar_image_url=None, current_avatar_tags=None, current_avatar_thumbnail_image_url=None, display_name=None, icon_frame=None, icon_url=None, id=None, image_url=None, nameplate_effect=None, profile_effect=None, profile_pic_override=None, status=None, status_description=None, local_vars_configuration=None):  # noqa: E501
        """MutualFriend - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._avatar_thumbnail = None
        self._banner_color = None
        self._banner_type = None
        self._current_avatar_image_url = None
        self._current_avatar_tags = None
        self._current_avatar_thumbnail_image_url = None
        self._display_name = None
        self._icon_frame = None
        self._icon_url = None
        self._id = None
        self._image_url = None
        self._nameplate_effect = None
        self._profile_effect = None
        self._profile_pic_override = None
        self._status = None
        self._status_description = None
        self.discriminator = None

        if avatar_thumbnail is not None:
            self.avatar_thumbnail = avatar_thumbnail
        if banner_color is not None:
            self.banner_color = banner_color
        if banner_type is not None:
            self.banner_type = banner_type
        self.current_avatar_image_url = current_avatar_image_url
        if current_avatar_tags is not None:
            self.current_avatar_tags = current_avatar_tags
        if current_avatar_thumbnail_image_url is not None:
            self.current_avatar_thumbnail_image_url = current_avatar_thumbnail_image_url
        self.display_name = display_name
        if icon_frame is not None:
            self.icon_frame = icon_frame
        if icon_url is not None:
            self.icon_url = icon_url
        self.id = id
        self.image_url = image_url
        if nameplate_effect is not None:
            self.nameplate_effect = nameplate_effect
        if profile_effect is not None:
            self.profile_effect = profile_effect
        if profile_pic_override is not None:
            self.profile_pic_override = profile_pic_override
        self.status = status
        self.status_description = status_description

    @property
    def avatar_thumbnail(self):
        """Gets the avatar_thumbnail of this MutualFriend.  # noqa: E501

        When profilePicOverride is not empty, use it instead.  # noqa: E501

        :return: The avatar_thumbnail of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._avatar_thumbnail

    @avatar_thumbnail.setter
    def avatar_thumbnail(self, avatar_thumbnail):
        """Sets the avatar_thumbnail of this MutualFriend.

        When profilePicOverride is not empty, use it instead.  # noqa: E501

        :param avatar_thumbnail: The avatar_thumbnail of this MutualFriend.  # noqa: E501
        :type avatar_thumbnail: str
        """

        self._avatar_thumbnail = avatar_thumbnail

    @property
    def banner_color(self):
        """Gets the banner_color of this MutualFriend.  # noqa: E501

        Hex colour without a leading `#`.  # noqa: E501

        :return: The banner_color of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._banner_color

    @banner_color.setter
    def banner_color(self, banner_color):
        """Sets the banner_color of this MutualFriend.

        Hex colour without a leading `#`.  # noqa: E501

        :param banner_color: The banner_color of this MutualFriend.  # noqa: E501
        :type banner_color: str
        """

        self._banner_color = banner_color

    @property
    def banner_type(self):
        """Gets the banner_type of this MutualFriend.  # noqa: E501


        :return: The banner_type of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._banner_type

    @banner_type.setter
    def banner_type(self, banner_type):
        """Sets the banner_type of this MutualFriend.


        :param banner_type: The banner_type of this MutualFriend.  # noqa: E501
        :type banner_type: str
        """

        self._banner_type = banner_type

    @property
    def current_avatar_image_url(self):
        """Gets the current_avatar_image_url of this MutualFriend.  # noqa: E501

        When profilePicOverride is not empty, use it instead.  # noqa: E501

        :return: The current_avatar_image_url of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._current_avatar_image_url

    @current_avatar_image_url.setter
    def current_avatar_image_url(self, current_avatar_image_url):
        """Sets the current_avatar_image_url of this MutualFriend.

        When profilePicOverride is not empty, use it instead.  # noqa: E501

        :param current_avatar_image_url: The current_avatar_image_url of this MutualFriend.  # noqa: E501
        :type current_avatar_image_url: str
        """
        if self.local_vars_configuration.client_side_validation and current_avatar_image_url is None:  # noqa: E501
            raise ValueError("Invalid value for `current_avatar_image_url`, must not be `None`")  # noqa: E501

        self._current_avatar_image_url = current_avatar_image_url

    @property
    def current_avatar_tags(self):
        """Gets the current_avatar_tags of this MutualFriend.  # noqa: E501


        :return: The current_avatar_tags of this MutualFriend.  # noqa: E501
        :rtype: list[str]
        """
        return self._current_avatar_tags

    @current_avatar_tags.setter
    def current_avatar_tags(self, current_avatar_tags):
        """Sets the current_avatar_tags of this MutualFriend.


        :param current_avatar_tags: The current_avatar_tags of this MutualFriend.  # noqa: E501
        :type current_avatar_tags: list[str]
        """

        self._current_avatar_tags = current_avatar_tags

    @property
    def current_avatar_thumbnail_image_url(self):
        """Gets the current_avatar_thumbnail_image_url of this MutualFriend.  # noqa: E501

        When profilePicOverride is not empty, use it instead.  # noqa: E501

        :return: The current_avatar_thumbnail_image_url of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._current_avatar_thumbnail_image_url

    @current_avatar_thumbnail_image_url.setter
    def current_avatar_thumbnail_image_url(self, current_avatar_thumbnail_image_url):
        """Sets the current_avatar_thumbnail_image_url of this MutualFriend.

        When profilePicOverride is not empty, use it instead.  # noqa: E501

        :param current_avatar_thumbnail_image_url: The current_avatar_thumbnail_image_url of this MutualFriend.  # noqa: E501
        :type current_avatar_thumbnail_image_url: str
        """

        self._current_avatar_thumbnail_image_url = current_avatar_thumbnail_image_url

    @property
    def display_name(self):
        """Gets the display_name of this MutualFriend.  # noqa: E501


        :return: The display_name of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this MutualFriend.


        :param display_name: The display_name of this MutualFriend.  # noqa: E501
        :type display_name: str
        """
        if self.local_vars_configuration.client_side_validation and display_name is None:  # noqa: E501
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def icon_frame(self):
        """Gets the icon_frame of this MutualFriend.  # noqa: E501


        :return: The icon_frame of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._icon_frame

    @icon_frame.setter
    def icon_frame(self, icon_frame):
        """Sets the icon_frame of this MutualFriend.


        :param icon_frame: The icon_frame of this MutualFriend.  # noqa: E501
        :type icon_frame: str
        """

        self._icon_frame = icon_frame

    @property
    def icon_url(self):
        """Gets the icon_url of this MutualFriend.  # noqa: E501


        :return: The icon_url of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._icon_url

    @icon_url.setter
    def icon_url(self, icon_url):
        """Sets the icon_url of this MutualFriend.


        :param icon_url: The icon_url of this MutualFriend.  # noqa: E501
        :type icon_url: str
        """

        self._icon_url = icon_url

    @property
    def id(self):
        """Gets the id of this MutualFriend.  # noqa: E501

        A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.  # noqa: E501

        :return: The id of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MutualFriend.

        A users unique ID, usually in the form of `usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469`. Legacy players can have old IDs in the form of `8JoV9XEdpo`. The ID can never be changed.  # noqa: E501

        :param id: The id of this MutualFriend.  # noqa: E501
        :type id: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def image_url(self):
        """Gets the image_url of this MutualFriend.  # noqa: E501


        :return: The image_url of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this MutualFriend.


        :param image_url: The image_url of this MutualFriend.  # noqa: E501
        :type image_url: str
        """
        if self.local_vars_configuration.client_side_validation and image_url is None:  # noqa: E501
            raise ValueError("Invalid value for `image_url`, must not be `None`")  # noqa: E501

        self._image_url = image_url

    @property
    def nameplate_effect(self):
        """Gets the nameplate_effect of this MutualFriend.  # noqa: E501


        :return: The nameplate_effect of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._nameplate_effect

    @nameplate_effect.setter
    def nameplate_effect(self, nameplate_effect):
        """Sets the nameplate_effect of this MutualFriend.


        :param nameplate_effect: The nameplate_effect of this MutualFriend.  # noqa: E501
        :type nameplate_effect: str
        """

        self._nameplate_effect = nameplate_effect

    @property
    def profile_effect(self):
        """Gets the profile_effect of this MutualFriend.  # noqa: E501


        :return: The profile_effect of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._profile_effect

    @profile_effect.setter
    def profile_effect(self, profile_effect):
        """Sets the profile_effect of this MutualFriend.


        :param profile_effect: The profile_effect of this MutualFriend.  # noqa: E501
        :type profile_effect: str
        """

        self._profile_effect = profile_effect

    @property
    def profile_pic_override(self):
        """Gets the profile_pic_override of this MutualFriend.  # noqa: E501


        :return: The profile_pic_override of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._profile_pic_override

    @profile_pic_override.setter
    def profile_pic_override(self, profile_pic_override):
        """Sets the profile_pic_override of this MutualFriend.


        :param profile_pic_override: The profile_pic_override of this MutualFriend.  # noqa: E501
        :type profile_pic_override: str
        """

        self._profile_pic_override = profile_pic_override

    @property
    def status(self):
        """Gets the status of this MutualFriend.  # noqa: E501


        :return: The status of this MutualFriend.  # noqa: E501
        :rtype: UserStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MutualFriend.


        :param status: The status of this MutualFriend.  # noqa: E501
        :type status: UserStatus
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def status_description(self):
        """Gets the status_description of this MutualFriend.  # noqa: E501


        :return: The status_description of this MutualFriend.  # noqa: E501
        :rtype: str
        """
        return self._status_description

    @status_description.setter
    def status_description(self, status_description):
        """Sets the status_description of this MutualFriend.


        :param status_description: The status_description of this MutualFriend.  # noqa: E501
        :type status_description: str
        """
        if self.local_vars_configuration.client_side_validation and status_description is None:  # noqa: E501
            raise ValueError("Invalid value for `status_description`, must not be `None`")  # noqa: E501

        self._status_description = status_description

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MutualFriend):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MutualFriend):
            return True

        return self.to_dict() != other.to_dict()
