# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.7
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class PurchaseProductListingRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'listing_id': 'str',
        'quantity': 'int',
        'total_price': 'int'
    }

    attribute_map = {
        'listing_id': 'listingId',
        'quantity': 'quantity',
        'total_price': 'totalPrice'
    }

    def __init__(self, listing_id=None, quantity=1, total_price=None, local_vars_configuration=None):  # noqa: E501
        """PurchaseProductListingRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._listing_id = None
        self._quantity = None
        self._total_price = None
        self.discriminator = None

        self.listing_id = listing_id
        self.quantity = quantity
        self.total_price = total_price

    @property
    def listing_id(self):
        """Gets the listing_id of this PurchaseProductListingRequest.  # noqa: E501


        :return: The listing_id of this PurchaseProductListingRequest.  # noqa: E501
        :rtype: str
        """
        return self._listing_id

    @listing_id.setter
    def listing_id(self, listing_id):
        """Sets the listing_id of this PurchaseProductListingRequest.


        :param listing_id: The listing_id of this PurchaseProductListingRequest.  # noqa: E501
        :type listing_id: str
        """
        if self.local_vars_configuration.client_side_validation and listing_id is None:  # noqa: E501
            raise ValueError("Invalid value for `listing_id`, must not be `None`")  # noqa: E501

        self._listing_id = listing_id

    @property
    def quantity(self):
        """Gets the quantity of this PurchaseProductListingRequest.  # noqa: E501


        :return: The quantity of this PurchaseProductListingRequest.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this PurchaseProductListingRequest.


        :param quantity: The quantity of this PurchaseProductListingRequest.  # noqa: E501
        :type quantity: int
        """
        if self.local_vars_configuration.client_side_validation and quantity is None:  # noqa: E501
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                quantity is not None and quantity > 99):  # noqa: E501
            raise ValueError("Invalid value for `quantity`, must be a value less than or equal to `99`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                quantity is not None and quantity < 1):  # noqa: E501
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")  # noqa: E501

        self._quantity = quantity

    @property
    def total_price(self):
        """Gets the total_price of this PurchaseProductListingRequest.  # noqa: E501


        :return: The total_price of this PurchaseProductListingRequest.  # noqa: E501
        :rtype: int
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this PurchaseProductListingRequest.


        :param total_price: The total_price of this PurchaseProductListingRequest.  # noqa: E501
        :type total_price: int
        """
        if self.local_vars_configuration.client_side_validation and total_price is None:  # noqa: E501
            raise ValueError("Invalid value for `total_price`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                total_price is not None and total_price < 0):  # noqa: E501
            raise ValueError("Invalid value for `total_price`, must be a value greater than or equal to `0`")  # noqa: E501

        self._total_price = total_price

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PurchaseProductListingRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PurchaseProductListingRequest):
            return True

        return self.to_dict() != other.to_dict()
