# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.0
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class TokenBundle(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'steam_item_id': 'str',
        'oculus_sku': 'str',
        'google_product_id': 'str',
        'amount': 'int',
        'description': 'str',
        'tokens': 'int',
        'image_url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'steam_item_id': 'steamItemId',
        'oculus_sku': 'oculusSku',
        'google_product_id': 'googleProductId',
        'amount': 'amount',
        'description': 'description',
        'tokens': 'tokens',
        'image_url': 'imageUrl'
    }

    def __init__(self, id=None, steam_item_id=None, oculus_sku=None, google_product_id=None, amount=None, description=None, tokens=None, image_url=None, local_vars_configuration=None):  # noqa: E501
        """TokenBundle - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._steam_item_id = None
        self._oculus_sku = None
        self._google_product_id = None
        self._amount = None
        self._description = None
        self._tokens = None
        self._image_url = None
        self.discriminator = None

        self.id = id
        self.steam_item_id = steam_item_id
        self.oculus_sku = oculus_sku
        if google_product_id is not None:
            self.google_product_id = google_product_id
        self.amount = amount
        self.description = description
        self.tokens = tokens
        self.image_url = image_url

    @property
    def id(self):
        """Gets the id of this TokenBundle.  # noqa: E501


        :return: The id of this TokenBundle.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TokenBundle.


        :param id: The id of this TokenBundle.  # noqa: E501
        :type id: str
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def steam_item_id(self):
        """Gets the steam_item_id of this TokenBundle.  # noqa: E501


        :return: The steam_item_id of this TokenBundle.  # noqa: E501
        :rtype: str
        """
        return self._steam_item_id

    @steam_item_id.setter
    def steam_item_id(self, steam_item_id):
        """Sets the steam_item_id of this TokenBundle.


        :param steam_item_id: The steam_item_id of this TokenBundle.  # noqa: E501
        :type steam_item_id: str
        """
        if self.local_vars_configuration.client_side_validation and steam_item_id is None:  # noqa: E501
            raise ValueError("Invalid value for `steam_item_id`, must not be `None`")  # noqa: E501

        self._steam_item_id = steam_item_id

    @property
    def oculus_sku(self):
        """Gets the oculus_sku of this TokenBundle.  # noqa: E501


        :return: The oculus_sku of this TokenBundle.  # noqa: E501
        :rtype: str
        """
        return self._oculus_sku

    @oculus_sku.setter
    def oculus_sku(self, oculus_sku):
        """Sets the oculus_sku of this TokenBundle.


        :param oculus_sku: The oculus_sku of this TokenBundle.  # noqa: E501
        :type oculus_sku: str
        """
        if self.local_vars_configuration.client_side_validation and oculus_sku is None:  # noqa: E501
            raise ValueError("Invalid value for `oculus_sku`, must not be `None`")  # noqa: E501

        self._oculus_sku = oculus_sku

    @property
    def google_product_id(self):
        """Gets the google_product_id of this TokenBundle.  # noqa: E501


        :return: The google_product_id of this TokenBundle.  # noqa: E501
        :rtype: str
        """
        return self._google_product_id

    @google_product_id.setter
    def google_product_id(self, google_product_id):
        """Sets the google_product_id of this TokenBundle.


        :param google_product_id: The google_product_id of this TokenBundle.  # noqa: E501
        :type google_product_id: str
        """

        self._google_product_id = google_product_id

    @property
    def amount(self):
        """Gets the amount of this TokenBundle.  # noqa: E501

        price of the bundle  # noqa: E501

        :return: The amount of this TokenBundle.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this TokenBundle.

        price of the bundle  # noqa: E501

        :param amount: The amount of this TokenBundle.  # noqa: E501
        :type amount: int
        """
        if self.local_vars_configuration.client_side_validation and amount is None:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def description(self):
        """Gets the description of this TokenBundle.  # noqa: E501


        :return: The description of this TokenBundle.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TokenBundle.


        :param description: The description of this TokenBundle.  # noqa: E501
        :type description: str
        """
        if self.local_vars_configuration.client_side_validation and description is None:  # noqa: E501
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def tokens(self):
        """Gets the tokens of this TokenBundle.  # noqa: E501

        number of tokens received  # noqa: E501

        :return: The tokens of this TokenBundle.  # noqa: E501
        :rtype: int
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens):
        """Sets the tokens of this TokenBundle.

        number of tokens received  # noqa: E501

        :param tokens: The tokens of this TokenBundle.  # noqa: E501
        :type tokens: int
        """
        if self.local_vars_configuration.client_side_validation and tokens is None:  # noqa: E501
            raise ValueError("Invalid value for `tokens`, must not be `None`")  # noqa: E501

        self._tokens = tokens

    @property
    def image_url(self):
        """Gets the image_url of this TokenBundle.  # noqa: E501

        direct url to image  # noqa: E501

        :return: The image_url of this TokenBundle.  # noqa: E501
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url):
        """Sets the image_url of this TokenBundle.

        direct url to image  # noqa: E501

        :param image_url: The image_url of this TokenBundle.  # noqa: E501
        :type image_url: str
        """
        if self.local_vars_configuration.client_side_validation and image_url is None:  # noqa: E501
            raise ValueError("Invalid value for `image_url`, must not be `None`")  # noqa: E501

        self._image_url = image_url

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenBundle):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TokenBundle):
            return True

        return self.to_dict() != other.to_dict()
