# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.9
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class TutorialStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'completed': 'bool',
        'completed_any_tutorial': 'bool',
        'completed_tutorials': 'list[str]',
        'tutorial_key': 'str'
    }

    attribute_map = {
        'completed': 'completed',
        'completed_any_tutorial': 'completedAnyTutorial',
        'completed_tutorials': 'completedTutorials',
        'tutorial_key': 'tutorialKey'
    }

    def __init__(self, completed=None, completed_any_tutorial=None, completed_tutorials=None, tutorial_key='undefined:undefined:v1', local_vars_configuration=None):  # noqa: E501
        """TutorialStatus - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._completed = None
        self._completed_any_tutorial = None
        self._completed_tutorials = None
        self._tutorial_key = None
        self.discriminator = None

        self.completed = completed
        self.completed_any_tutorial = completed_any_tutorial
        self.completed_tutorials = completed_tutorials
        self.tutorial_key = tutorial_key

    @property
    def completed(self):
        """Gets the completed of this TutorialStatus.  # noqa: E501


        :return: The completed of this TutorialStatus.  # noqa: E501
        :rtype: bool
        """
        return self._completed

    @completed.setter
    def completed(self, completed):
        """Sets the completed of this TutorialStatus.


        :param completed: The completed of this TutorialStatus.  # noqa: E501
        :type completed: bool
        """
        if self.local_vars_configuration.client_side_validation and completed is None:  # noqa: E501
            raise ValueError("Invalid value for `completed`, must not be `None`")  # noqa: E501

        self._completed = completed

    @property
    def completed_any_tutorial(self):
        """Gets the completed_any_tutorial of this TutorialStatus.  # noqa: E501


        :return: The completed_any_tutorial of this TutorialStatus.  # noqa: E501
        :rtype: bool
        """
        return self._completed_any_tutorial

    @completed_any_tutorial.setter
    def completed_any_tutorial(self, completed_any_tutorial):
        """Sets the completed_any_tutorial of this TutorialStatus.


        :param completed_any_tutorial: The completed_any_tutorial of this TutorialStatus.  # noqa: E501
        :type completed_any_tutorial: bool
        """
        if self.local_vars_configuration.client_side_validation and completed_any_tutorial is None:  # noqa: E501
            raise ValueError("Invalid value for `completed_any_tutorial`, must not be `None`")  # noqa: E501

        self._completed_any_tutorial = completed_any_tutorial

    @property
    def completed_tutorials(self):
        """Gets the completed_tutorials of this TutorialStatus.  # noqa: E501


        :return: The completed_tutorials of this TutorialStatus.  # noqa: E501
        :rtype: list[str]
        """
        return self._completed_tutorials

    @completed_tutorials.setter
    def completed_tutorials(self, completed_tutorials):
        """Sets the completed_tutorials of this TutorialStatus.


        :param completed_tutorials: The completed_tutorials of this TutorialStatus.  # noqa: E501
        :type completed_tutorials: list[str]
        """
        if self.local_vars_configuration.client_side_validation and completed_tutorials is None:  # noqa: E501
            raise ValueError("Invalid value for `completed_tutorials`, must not be `None`")  # noqa: E501

        self._completed_tutorials = completed_tutorials

    @property
    def tutorial_key(self):
        """Gets the tutorial_key of this TutorialStatus.  # noqa: E501

        The ID of a tutorial, in the format `{platform}:{tutorial}:{version}`. `undefined:undefined:v1` is used as a null-ish or sentinel value.  # noqa: E501

        :return: The tutorial_key of this TutorialStatus.  # noqa: E501
        :rtype: str
        """
        return self._tutorial_key

    @tutorial_key.setter
    def tutorial_key(self, tutorial_key):
        """Sets the tutorial_key of this TutorialStatus.

        The ID of a tutorial, in the format `{platform}:{tutorial}:{version}`. `undefined:undefined:v1` is used as a null-ish or sentinel value.  # noqa: E501

        :param tutorial_key: The tutorial_key of this TutorialStatus.  # noqa: E501
        :type tutorial_key: str
        """
        if self.local_vars_configuration.client_side_validation and tutorial_key is None:  # noqa: E501
            raise ValueError("Invalid value for `tutorial_key`, must not be `None`")  # noqa: E501

        self._tutorial_key = tutorial_key

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TutorialStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TutorialStatus):
            return True

        return self.to_dict() != other.to_dict()
