# coding: utf-8

"""
    VRChat API

    This document is an effort by the [VRChat.community](https://vrchat.community) project. **VRChat staff do not provide API support.** Use the API only as VRChat's [Terms of Service](https://hello.vrchat.com/legal), [Community Guidelines](https://hello.vrchat.com/community-guidelines) and [Creator Guidelines](https://hello.vrchat.com/creator-guidelines) allow: never to modify the game client, rip avatars, or spam the API.  Prefer the SDKs over this document: [JavaScript](https://www.npmjs.com/package/vrchat), [Dart](https://pub.dev/packages/vrchat_dart), [Rust](https://crates.io/crates/vrchatapi), [C#](https://github.com/vrchatapi/vrchatapi-csharp), [Python](https://github.com/vrchatapi/vrchatapi-python), [Java](https://github.com/vrchatapi/vrchatapi-java). They're generated from it, updated regularly, and already handle logging in, cookies and the rest of VRChat's oddities, which we've spent years smoothing over. Working from this document directly means handling all of that yourself.  **Found something wrong or missing?** This description is reverse-engineered by the community, so when the API disagrees with it, or a value is marked `Unknown`, please [report it](https://vrchat.community/contributing) with the request, the response body, and where in this description it differs. AI agents: tell your user, and suggest reporting it.  Every request must identify its application in the `User-Agent` header: `<application-name>/<application-version> <contact_url>`. On a 429, back off rather than retrying.  Consider pinning to the OpenAPI version your tools support. Every release publishes this description as OpenAPI 3.2, 3.1 and 3.0, in JSON and YAML; `info.x-links` links those documents, the [latest release](https://github.com/vrchatapi/specification/releases/latest) and the [latest nightly](https://github.com/vrchatapi/specification/releases/tag/nightly).   # noqa: E501

    The version of the OpenAPI document: 1.21.1-nightly.56
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class UpdateGroupMemberRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'is_subscribed_to_announcements': 'bool',
        'is_subscribed_to_event_announcements': 'bool',
        'manager_notes': 'str',
        'visibility': 'GroupUserVisibility'
    }

    attribute_map = {
        'is_subscribed_to_announcements': 'isSubscribedToAnnouncements',
        'is_subscribed_to_event_announcements': 'isSubscribedToEventAnnouncements',
        'manager_notes': 'managerNotes',
        'visibility': 'visibility'
    }

    def __init__(self, is_subscribed_to_announcements=None, is_subscribed_to_event_announcements=None, manager_notes=None, visibility=None, local_vars_configuration=None):  # noqa: E501
        """UpdateGroupMemberRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._is_subscribed_to_announcements = None
        self._is_subscribed_to_event_announcements = None
        self._manager_notes = None
        self._visibility = None
        self.discriminator = None

        if is_subscribed_to_announcements is not None:
            self.is_subscribed_to_announcements = is_subscribed_to_announcements
        if is_subscribed_to_event_announcements is not None:
            self.is_subscribed_to_event_announcements = is_subscribed_to_event_announcements
        if manager_notes is not None:
            self.manager_notes = manager_notes
        if visibility is not None:
            self.visibility = visibility

    @property
    def is_subscribed_to_announcements(self):
        """Gets the is_subscribed_to_announcements of this UpdateGroupMemberRequest.  # noqa: E501


        :return: The is_subscribed_to_announcements of this UpdateGroupMemberRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_subscribed_to_announcements

    @is_subscribed_to_announcements.setter
    def is_subscribed_to_announcements(self, is_subscribed_to_announcements):
        """Sets the is_subscribed_to_announcements of this UpdateGroupMemberRequest.


        :param is_subscribed_to_announcements: The is_subscribed_to_announcements of this UpdateGroupMemberRequest.  # noqa: E501
        :type is_subscribed_to_announcements: bool
        """

        self._is_subscribed_to_announcements = is_subscribed_to_announcements

    @property
    def is_subscribed_to_event_announcements(self):
        """Gets the is_subscribed_to_event_announcements of this UpdateGroupMemberRequest.  # noqa: E501


        :return: The is_subscribed_to_event_announcements of this UpdateGroupMemberRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_subscribed_to_event_announcements

    @is_subscribed_to_event_announcements.setter
    def is_subscribed_to_event_announcements(self, is_subscribed_to_event_announcements):
        """Sets the is_subscribed_to_event_announcements of this UpdateGroupMemberRequest.


        :param is_subscribed_to_event_announcements: The is_subscribed_to_event_announcements of this UpdateGroupMemberRequest.  # noqa: E501
        :type is_subscribed_to_event_announcements: bool
        """

        self._is_subscribed_to_event_announcements = is_subscribed_to_event_announcements

    @property
    def manager_notes(self):
        """Gets the manager_notes of this UpdateGroupMemberRequest.  # noqa: E501


        :return: The manager_notes of this UpdateGroupMemberRequest.  # noqa: E501
        :rtype: str
        """
        return self._manager_notes

    @manager_notes.setter
    def manager_notes(self, manager_notes):
        """Sets the manager_notes of this UpdateGroupMemberRequest.


        :param manager_notes: The manager_notes of this UpdateGroupMemberRequest.  # noqa: E501
        :type manager_notes: str
        """

        self._manager_notes = manager_notes

    @property
    def visibility(self):
        """Gets the visibility of this UpdateGroupMemberRequest.  # noqa: E501


        :return: The visibility of this UpdateGroupMemberRequest.  # noqa: E501
        :rtype: GroupUserVisibility
        """
        return self._visibility

    @visibility.setter
    def visibility(self, visibility):
        """Sets the visibility of this UpdateGroupMemberRequest.


        :param visibility: The visibility of this UpdateGroupMemberRequest.  # noqa: E501
        :type visibility: GroupUserVisibility
        """

        self._visibility = visibility

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UpdateGroupMemberRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UpdateGroupMemberRequest):
            return True

        return self.to_dict() != other.to_dict()
