# coding: utf-8

"""
    VRChat API Documentation


    The version of the OpenAPI document: 1.20.0
    Contact: vrchatapi.lpv0t@aries.fyi
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from vrchatapi.configuration import Configuration


class UserExists(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'user_exists': 'bool',
        'name_ok': 'bool'
    }

    attribute_map = {
        'user_exists': 'userExists',
        'name_ok': 'nameOk'
    }

    def __init__(self, user_exists=False, name_ok=False, local_vars_configuration=None):  # noqa: E501
        """UserExists - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._user_exists = None
        self._name_ok = None
        self.discriminator = None

        self.user_exists = user_exists
        if name_ok is not None:
            self.name_ok = name_ok

    @property
    def user_exists(self):
        """Gets the user_exists of this UserExists.  # noqa: E501

        Status if a user exist with that username or userId.  # noqa: E501

        :return: The user_exists of this UserExists.  # noqa: E501
        :rtype: bool
        """
        return self._user_exists

    @user_exists.setter
    def user_exists(self, user_exists):
        """Sets the user_exists of this UserExists.

        Status if a user exist with that username or userId.  # noqa: E501

        :param user_exists: The user_exists of this UserExists.  # noqa: E501
        :type user_exists: bool
        """
        if self.local_vars_configuration.client_side_validation and user_exists is None:  # noqa: E501
            raise ValueError("Invalid value for `user_exists`, must not be `None`")  # noqa: E501

        self._user_exists = user_exists

    @property
    def name_ok(self):
        """Gets the name_ok of this UserExists.  # noqa: E501

        Is the username valid?  # noqa: E501

        :return: The name_ok of this UserExists.  # noqa: E501
        :rtype: bool
        """
        return self._name_ok

    @name_ok.setter
    def name_ok(self, name_ok):
        """Sets the name_ok of this UserExists.

        Is the username valid?  # noqa: E501

        :param name_ok: The name_ok of this UserExists.  # noqa: E501
        :type name_ok: bool
        """

        self._name_ok = name_ok

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserExists):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserExists):
            return True

        return self.to_dict() != other.to_dict()
