on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main
    outputs:
      artifact:
        description: Download URL for the built distributions.
        value: ${{ jobs.build.outputs.artifact }}

name: CI

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-python
          ref: ${{ inputs.ref || github.ref }}

      - uses: vrchatapi/specification/.github/actions/setup-generator@ci/modernise-actions

      - uses: vrchatapi/specification/.github/actions/download@ci/modernise-actions
        with:
          bundle: openapi-legacy.yaml

      - run: bash ./generate.sh openapi-legacy.yaml "$(yq -r '.info.version' openapi-legacy.yaml)"

      - uses: actions/upload-artifact@v7
        with:
          name: generated-python
          path: .
          include-hidden-files: true

  build:
    needs: generate
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: generated-python

      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'
          cache: pip

      - run: python -m pip install build

      - run: python -m build

      - id: upload
        uses: actions/upload-artifact@v7
        with:
          name: dist-python
          path: dist

  install:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: dist-python
          path: dist

      - uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - run: python -m pip install dist/*.whl

      - run: python -c "import vrchatapi; print(vrchatapi.__name__)"
